### ISSUE TITLE
something wrong with the code

### ISSUE THREAD

**Issue by lifukang** [pierreay/reproduce-spectre-gem5#1]
I have tried to reproduce this project but got something wrong .           
I succeeded in doing everything well but i was trucked when executing these commands below.
cd "$reproduce_repo"/gem5
"$gem5_repo"/build/ARM/gem5.opt -q -d 01boot \
                                ./RPIv4.py -v --num-cores=4 --fs \
            --fs-kernel="$gem5_repo"/"$img_dir"/binaries/vmlinux.arm64 \
            --fs-disk-image="$gem5_repo"/"$img_dir"/linaro-minimal-aarch64.img \
            --fs-workload-image="$gem5_repo"/"$img_dir"/"$img"
I didn't know what happened.
![945643929b178fe3318181cf8c8fcca](https://user-images.githubusercontent.com/45821945/195023397-7ef2e926-1535-4675-a2d0-b462f3c6b7dc.jpg)
![917402b4d5f77aad372f09979b1eb25](https://user-images.githubusercontent.com/45821945/195023427-703175e6-a734-42c4-9b38-715365daff32.jpg)
![0eb14174d09485fb2f787b84773bc47](https://user-images.githubusercontent.com/45821945/195023596-bf50a381-b79d-46bd-8987-3eb889429c4a.jpg)

So i tried to run the RPIv4.python in SE mode,but got something wrong showed as below.So must i run your code in the FS mode.The bug is below. 
![0f30e7c4288a200aeab4f4befd780b5](https://user-images.githubusercontent.com/45821945/195023618-efdd193d-88b7-4fac-aa60-967cfd4a845d.jpg)

**Comment by pierreay** [comment]
I didn't update the project's code with the new gem5 versions. I suggest you to try with gem5 v20.0, the version I used for this project.
