### ISSUE TITLE
I can't find some classes

### ISSUE THREAD

**Issue by dnffabs** [pierreay/reproduce-spectre-gem5#2]
I did not conduct the experiment on Raspberry PI
I have tried to reproduce this project but got something wrong .
I tried to install gem5 on ubuntu20.04 to simulate your experiment, but there was a small bug with the code.
In python file ARMv8A_Cortex_A72.py, I can't find ArmDTB and ArmITB in m5.objects
I wonder if these two classes are in the gem5 library function？
I can't find these classes in my gem5 library.
Did you define these classes yourself?

**Comment by pierreay** [comment]
Hi!

Those classes are from the gem5 project. They should be available in your Python script if you used gem5 v20.0. Which version of gem5 do you use? I didn't remember which distribution I used at the time to install gem5 on, but what is important is the gem5 version, the distro and kernel running inside gem5, and on the raspberry pi.

Bests
Pierre

**Comment by dnffabs** [comment]
I installed v21.0 and just found the online files about these two classes. It seems that these two classes are not in the corresponding files because of the version problem. Now I am trying to modify it, thank you for your answer。

**Comment by pierreay** [comment]
No problem. ;)

**Comment by dnffabs** [comment]
![image](https://github.com/pierreay/reproduce-spectre-gem5/assets/141152881/c1b5a63f-2ef6-4f61-9228-9b39edaa5fe2)
I am also planning to reproduce the experiment on the Raspberry PI, but it seems that the image you provided cannot be successfully installed on the Raspberry PI 4B, so now I am trying to install the latest version of kali system on the Raspberry PI, will this affect the success of the experiment?

**Comment by dnffabs** [comment]
![IMG_1405](https://github.com/pierreay/reproduce-spectre-gem5/assets/141152881/c0122e5f-c95e-49fd-a1e1-d016f1a8920a)
After downloading the xz file using the torrent you provided, I encountered the above problems when installing it on the Raspberry PI 4B.

**Comment by pierreay** [comment]
This is another issue not related with the original thread, please do not continue in this one.

Anyway, this issue seems to be related to secure boot. This message seems emitted by the Linux kernel of the Raspberry Pi because the Kali Linux image is not signed with a key registered in the boot loader for the secure boot process. I would suggest to disable the secure boot process in the config.txt file of the Raspberry Pi. On my side, I never encountered this issue before.

**Comment by dnffabs** [comment]
ok，thanks，I have solved this problem
